apiVersion: v1
kind: Service
metadata:
  name: javawebapppodsvc
  labels:
    app: sample-app
spec:
  type: NodePort
  selector:
    app: javawebapp
  ports:
    - name: http
      protocol: TCP
      port: 80          # Service port
      targetPort: 8080  # Container port in the pod
      nodePort: 30036   # NodePort (optional). If not given, K8s will assign one between 30000–32767
